# Site settings
baseurl = "https://frankenbot.github.io/"
languageCode = "en-us"
title = "frankenbot"
themeDir = "themes"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-104972796-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Frankenbot"
  description = "A report on our UBC Engineering Physics 253 robot competition entry."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "frankenbotFavicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](https://frankenbot.github.io)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Team Frankenbot"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "About"
    portfolio = "Meet Frankenbot"
    about = "Timeline"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://localhost:1313/#"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://projectlab.engphys.ubc.ca/enph253-2017/competition-2017/"
      name = "ENPH 253"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "FRANKENBOT"
    subtitle = "Welcome to our website!"
    buttonText = "About"


  # Services section
  [params.services]
    enable = false
    title = "About"
    subtitle = "UBC Engineering Physics 253 Robot Competition 2017."

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Meet Frankenbot"
    subtitle = "Click the images below to learn more about the robot and our learning experience."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close"


    # About section
  [params.about]
    enable = true
    title = "Timeline"
    subtitle = "An outline of our progress throughout Summer"
    endpoint = "Aug 10<br>Competition!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "sketch.jpg"
      date = "June 1"
      title = "Brainstorming"
      description = "We collaborated as a group to design our robot, implementing various sketching techniques to create original ideas."

	[[params.about.events]]
      img = "3.jpg"
      date = "June 10-12"
      title = "Software Brainstorming and Organization"
      description = "We divided the competition into different stages and reflected that in our software design to allow for modularity. We also determined the various functions and classes needed, and designed state diagrams for each function."

    [[params.about.events]]
      img = "name.jpg"
      date = "June 23"
      title = "Design Proposal"
      description = "Submitted a document containing a full description of our mechanical, electrical, and software systems including torque calculations, circuit diagrams, mechanical sketches and software state diagrams."

    [[params.about.events]]
      img = "laser.jpg"
      date = "June 29"
      title = "Prototyping"
      description = "We began prototyping our mechanical parts, including the arm, winch, bucket and claw mechanisms."
	  
	[[params.about.events]]
      img = "backbone.jpg"
      date = "July 4-7"
      title = "Backbone Development"
      description = "In preparation for tape following, we modeled the chassis, wheels, and gears in OnShape, and laser cut the parts in addition to soldering and testing QRD sensors and H-Bridge circuits. We also built the zipline bucket, soldered and optimized the IR detection circuit to detect a 1 kHz signal up to 2.5m away from the IR blaster. "
	  
	[[params.about.events]]
      img = "tapeFollower.jpg"
      date = "July 11-14"
      title = "Construction and Extremeties Development"
      description = "We assembled our first chassis and began tuning PID parameters for tape following. We also built the winch mechanism that lifts the bucket to the zipline and continued the construction of the retrieval arm."
	  
	[[params.about.events]]
      img = "3.jpg"
      date = "July 15-16"
      title = "Software Development"
      description = "We wrote the first full draft of code for each section of the competition in separate files for ease of debugging. We later combined the states into a single document once we tested each section extensively during integration."
	  
	 [[params.about.events]]
      img = "zipline.jpg"
      date = "July 21"
      title = "Zipline Completion"
      description = "Zipline mechanism fully complete and controlled by switches."
	  
	[[params.about.events]]
      img = "clawConstruction.jpg"
      date = "July 24-27"
      title = "Arms and Eyes"
      description = "Finished construction of retrieval arm and claw prototype. Started to integrate IR detection into the main code."
	  
	[[params.about.events]]
      img = "timeTrials.jpg"
      date = "July 28"
      title = "Time Trials"
      description = "We showcased our progress to the instructors, demonstrating functionality in separate parts because the majority of our systems were not fully integrated."
	  
	[[params.about.events]]
      img = "arm.jpg"
      date = "July 31"
      title = "Retrieval Arm"
      description = "Solved the common ground problem with the retrieval arm, allowing for our first successful rescue of an agent."
	  
	[[params.about.events]]
      img = "completion.jpg"
      date = "August 1"
      title = "Integration Complete"
      description = "We successfully rescued six agents down the zipline for the first time!"
	  
	[[params.about.events]]
      img = "finalTouches.jpg"
      date = "August 2-9"
      title = "Final Touches"
      description = "Tuned Frankenbot's speed and arm precision in preparation for competition."


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Meet our team"
    description = "We are Engineering Physics students at the University of British Columbia.  Engineering Physics is a department in the Faculty of Applied Science at UBC that seeks to provide training in both electrical and mechanical engineering along with building a strong foundation in mathematics, physics, and applied technologies."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "adam.jpg"
      name = "Adam Fink"
        social = [
        ["fa-linkedin", "https://www.linkedin.com/in/adam-fink-8a0a16103"]
      ]

    [[params.team.members]]
      img = "ashleyHeadshot.jpg"
      name = "Ashley Lloyd"
        social = [
        ["fa-linkedin", "https://www.linkedin.com/in/ashley-lloyd-9059a6139"]
      ]

    [[params.team.members]]
      img = "rhiannon.jpg"
      name = "Rhiannon Holmes"
        social = [
        ["fa-linkedin", "https://www.linkedin.com/in/rhiannon-holmes-330251104/"]
      ]

    [[params.team.members]]
      img = "rikaHeadshot.jpg"
      name = "Rika Sugimoto"

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  #[params.contact]
   # enable = true
    #title = "Contact us"
    #subtitle  = "Lorem ipsum dolor sit amet consectetur."
    #buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    #email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    #[params.contact.form.name]
     # text = "Your Name *"
      #warning = "Please enter your name."

    #[params.contact.form.email]
     # text = "Your Email *"
      #warning = "Please enter your email address."

    #[params.contact.form.phone]
     # text = "Your Phone *"
      #warning = "Please enter your phone number."

    #[params.contact.form.message]
     # text = "Your Message *"
      #warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"